added import pipe to template
sesam-io/superoffice-connector pull request #6
Opened 2023-03-22 15:50 UTC by erik-leven

2023-03-22 18:19 UTC, BaardBouvet requested changes

2023-03-22 18:19 UTC, BaardBouvet commented on templates/quote.json
> +          "datatype": "GetQuoteEntity"
This should just live on the operation

2023-03-22 18:19 UTC, BaardBouvet commented on templates/quote.json
> +      "dataset": "{{@ system @}}-salelistQuote-collect",
Use lowercase names on pipes for now

2023-03-22 18:19 UTC, BaardBouvet commented on templates/quote.json
> +        "datatype": "sale",
These properties should live on the operation

2023-03-27 07:55 UTC, ellis-igneri approved these changes

2023-03-27 07:56 UTC, merged